title: &title Aleksandr Krivoshchekov (SuperPaintman) - superpaintman.com

email: SuperPaintmanDeveloper@gmail.com

seo:
    robots:
        index: true
        follow: true

    title: *title
    description: SuperPaintman's jumppad. Aleksandr Krivoshchekov's personal site.
    keywords:
        - SuperPaintman
        - Aleksandr Krivoshchekov
        - Krivoshchekov
        # Typos, mistakes and aliases
        # Yes, my first name is `Aleksandr` not `Alexander` :)
        # Yes, my last name is `Krivoshchekov` not `Krivoshhekov` :)
        - Alex Krivoshchekov
        - Alexander Krivoshchekov
        - Aleksandr Krivoshhekov
        - Alex Krivoshhekov
        - Alexander Krivoshhekov
        # - Александр Кривощеков
    local: en_US
    type: website
    url: https://superpaintman.com/
    site_name: Aleksandr Krivoshchekov (SuperPaintman)
    canonical: https://superpaintman.com/
    theme_color: "#333333"

    twitter:
        card: summary
        site: '@SuperPaintman'

content:
    title: ALEKSANDR KRIVOSHCHEKOV
    description: Lead Software Engineer

links:
    -
        id:    "github"
        title: "GitHub"
        name:  "SuperPaintman"
        url:   "https://github.com/SuperPaintman/"
    -
        id:    "linkedin"
        title: "LinkedIn"
        name:  "superpaintman"
        url:   "https://www.linkedin.com/in/superpaintman/"
    -
        id:    "telegram"
        title: "Telegram"
        name:  "superpaintman"
        url:   "https://t.me/superpaintman"
    -
        id:    "habrahabr"
        title: "Habrahabr"
        name:  "superpaintman"
        url:   "https://habr.com/en/users/superpaintman/"
    -
        id:    "medium"
        title: "Medium"
        name:  "SuperPaintman"
        url:   "https://medium.com/@SuperPaintman"
    # -
    #     id:    "vkontakte"
    #     title: "VKontakte"
    #     name:  "superpaintman"
    #     url:   "https://vk.com/superpaintman"
    -
        id:    "twitter"
        title: "Twitter"
        name:  "SuperPaintman"
        url:   "https://twitter.com/SuperPaintman"
    -
        id:    "instagram"
        title: "Instagram"
        name:  "superpaintman"
        url:   "https://www.instagram.com/superpaintman/"
    # -
    #     id:    "npm"
    #     title: "NPM"
    #     name:  "SuperPaintman"
    #     url:   "https://www.npmjs.com/~superpaintman"
    # -
    #     id:    "dockerhub"
    #     title: "Docker Hub"
    #     name:  "superpaintman"
    #     url:   "https://hub.docker.com/u/superpaintman/"
    # -
    #     id:   "headhunter"
    #     name: ""
    #     url:  ""

counters:
    yandex: 41936319
    google: "UA-89780612-1"

footer:
    repo:
        name: GitHub
        url: https://github.com/SuperPaintman/superpaintman.com

    license:
        text: "Apache License, Version 2.0"
        url: https://raw.githubusercontent.com/SuperPaintman/superpaintman.com/master/LICENSE
