title: &title Aleksandr Krivoshchekov (SuperPaintman) - superpaintman.com

seo:
    robots:
        index: true
        follow: true

    title: *title
    description: SuperPaintman's jumppad. Aleksandr Krivoshchekov's personal site.
    keywords:
        - SuperPaintman
        - Aleksandr Krivoshchekov
        - Krivoshchekov
        # Typos, mistakes and aliases
        # Yes, my first name is `Aleksandr` not `Alexander` :)
        # Yes, my last name is `Krivoshchekov` not `Krivoshhekov` :)
        - Alex Krivoshchekov
        - Alexander Krivoshchekov
        - Aleksandr Krivoshhekov
        - Alex Krivoshhekov
        - Alexander Krivoshhekov
        # - Александр Кривощеков
    local: en_US
    type: website
    url: https://superpaintman.com/
    site_name: Aleksandr Krivoshchekov (SuperPaintman)
    canonical: https://superpaintman.com/
    theme_color: "#333333"

    twitter:
        card: summary
        site: '@SuperPaintman'

links:
    github:
        title: "GitHub"
        name:  "SuperPaintman"
        url:   "https://github.com/SuperPaintman/"
    linkedin:
        title: "LinkedIn"
        name:  "superpaintman"
        url:   "https://www.linkedin.com/in/superpaintman/"
    habrahabr:
        title: "Habrahabr"
        name:  "superpaintman"
        url:   "https://habrahabr.ru/users/superpaintman/"
    medium:
        title: "Medium"
        name:  "SuperPaintman"
        url:   "https://medium.com/@SuperPaintman"
    vkontakte:
        title: "VKontakte"
        name:  "superpaintman"
        url:   "https://vk.com/superpaintman"
    twitter:
        title: "Twitter"
        name:  "SuperPaintman"
        url:   "https://twitter.com/SuperPaintman"
    npm:
        title: "NPM"
        name:  "SuperPaintman"
        url:   "https://www.npmjs.com/~superpaintman"
    # dockerhub:
    #     title: "Docker Hub"
    #     name:  "superpaintman"
    #     url:   "https://hub.docker.com/u/superpaintman/"
    # headhunter:
    #     name: ""
    #     url:  ""

counters:
    yandex: 41936319
    google: "UA-89780612-1"

footer:
    repo:
        name: GitHub
        url: https://github.com/SuperPaintman/superpaintman.com

    license:
        text: "Apache License, Version 2.0"
        url: https://raw.githubusercontent.com/SuperPaintman/superpaintman.com/master/LICENSE
